export const SET_AMOUNT = "SET_AMOUNT";
export const GET_AMOUNT = "GET_AMOUNT";
export const SET_DEBIT_ACCOUNT = "SET_DEBIT_ACCOUNT";
export const GET_DEBIT_ACCOUNT = "GET_DEBIT_ACCOUNT";
export const SET_CREDIT_ACCOUNT = "SET_CREDIT_ACCOUNT";
export const GET_CREDIT_ACCOUNT = "GET_CREDIT_ACCOUNT";